spring:
  liquibase:
    enabled: true
    user: postgres
    password: postgres
  datasource:
    url: 'jdbc:postgresql://localhost:5432/voice'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          frame-state-client:
            url: http://localhost:8082
  kafka:
    bootstrap-servers: localhost:9092

voice:
  kafka:
    authentication:
      username: admin
      password: admin
    producer:
      topic: topic
