apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KTX_APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${KTX_APP_NAME}
  template:
    metadata:
      labels:
        app: ${KTX_APP_NAME}
    spec:
      containers:
        - name: ${KTX_APP_NAME}
          image: ${KTX_IMAGE_NAME}:${KTX_IMAGE_VERSION}
          imagePullPolicy: Never
          command: ["java","-Dspring.profiles.active=${KTX_APP_PROFILE}","-jar","/app.jar"]
          ports:
            - containerPort: 8080
          env:
            - name: DB_ADDRESS
              value: ${DB_ADDRESS}
            - name: DB_NAME
              value: ${DB_NAME}
            - name: DB_USER
              value: ${DB_USER}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: KTX_STATE_SVC_URL
              value: ${KTX_STATE_SVC_URL}