apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KTX_APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${KTX_APP_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        checksum/config: ${KTX_CONFIG_HASH}
      labels:
        app: ${KTX_APP_NAME}
    spec:
      containers:
        - name: ${KTX_APP_NAME}
          image: ${KTX_IMAGE_NAME}:${KTX_IMAGE_VERSION}
          imagePullPolicy: Never
          command: ["java", "-jar", "/app.jar"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: ${KTX_APP_NAME}
            items:
              - key: application.yaml
                path: application.yaml
